### ISSUE TITLE
License information?

### ISSUE THREAD

**Issue by jbqueru** [gwEm303/maxYMiser_replay#2]
I see that you've made plenty of source code available. However, I haven't been able to find any license information anywhere, such that I'm not comfortable using your code. Did you intend to use any specific license? If that's not been on your radar yet, good choices might be MIT (very simple), Apache 2.0 (solid patent protection), of LGPL v3 (requires that people who make changes to the player make such changes available with what they ship).

**Comment by gwEm303** [comment]
There is no license, I am retaining all rights. This is a demoscene project, if you feel uncomfortable using the source then I understand. Alternatively drop me an email and we can work something out.
